# Generated by Django 2.0.5 on 2018-07-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0002_auto_20180711_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apistep',
            name='apiresult',
            field=models.CharField(max_length=5000, verbose_name='预期结果'),
        ),
    ]
