# Generated by Django 2.0.5 on 2018-07-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0004_auto_20180711_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apistep',
            name='apiparamvalue',
            field=models.CharField(max_length=800, verbose_name='请求参数和值'),
        ),
        migrations.AlterField(
            model_name='apistep',
            name='apiresult',
            field=models.CharField(max_length=800, verbose_name='预期结果'),
        ),
    ]
