# Generated by Django 2.0.5 on 2018-07-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0005_auto_20180711_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apistep',
            name='apiresult',
            field=models.CharField(max_length=200, verbose_name='预期结果'),
        ),
        migrations.AlterField(
            model_name='apistep',
            name='apiurl',
            field=models.CharField(max_length=200, verbose_name='接口地址'),
        ),
    ]
