# Generated by Django 2.0.5 on 2018-07-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0006_auto_20180711_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apistep',
            name='apimethod',
            field=models.CharField(choices=[('get', 'get'), ('post', 'post'), ('put', 'put'), ('delete', 'delete'), ('patch', 'patch')], default='get', max_length=64, null=True, verbose_name='请求方法'),
        ),
        migrations.AlterField(
            model_name='apistep',
            name='apiname',
            field=models.CharField(max_length=64, verbose_name='接口名称'),
        ),
        migrations.AlterField(
            model_name='apistep',
            name='apiparamvalue',
            field=models.CharField(max_length=64, verbose_name='请求参数和值'),
        ),
        migrations.AlterField(
            model_name='apistep',
            name='apiresult',
            field=models.CharField(max_length=64, verbose_name='预期结果'),
        ),
        migrations.AlterField(
            model_name='apistep',
            name='apiurl',
            field=models.CharField(max_length=64, verbose_name='接口地址'),
        ),
    ]
