# Generated by Django 2.0.5 on 2018-07-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0008_auto_20180711_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apistep',
            name='apimethod',
            field=models.CharField(choices=[('get', 'get'), ('post', 'post'), ('put', 'put'), ('delete', 'delete'), ('patch', 'patch')], default='get', max_length=200, null=True, verbose_name='请求方法'),
        ),
        migrations.AlterField(
            model_name='apistep',
            name='apiname',
            field=models.CharField(max_length=100, verbose_name='接口名称'),
        ),
        migrations.AlterField(
            model_name='apistep',
            name='apiparamvalue',
            field=models.CharField(max_length=800, verbose_name='请求参数和值'),
        ),
        migrations.AlterField(
            model_name='apistep',
            name='apiresult',
            field=models.CharField(max_length=1000, verbose_name='预期结果'),
        ),
        migrations.AlterField(
            model_name='apistep',
            name='apistatus',
            field=models.BooleanField(max_length=128, verbose_name='是否通过'),
        ),
        migrations.AlterField(
            model_name='apistep',
            name='apiurl',
            field=models.CharField(max_length=500, verbose_name='接口地址'),
        ),
        migrations.AlterField(
            model_name='apitest',
            name='apitestdesc',
            field=models.CharField(max_length=64, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='apitest',
            name='apitestname',
            field=models.CharField(max_length=64, verbose_name='流程接口名称'),
        ),
        migrations.AlterField(
            model_name='apitest',
            name='apitestresult',
            field=models.BooleanField(max_length=128, verbose_name='测试结果'),
        ),
    ]
