# Generated by Django 2.0.5 on 2018-07-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0009_auto_20180711_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apistep',
            name='apistatus',
            field=models.BooleanField(verbose_name='是否通过'),
        ),
        migrations.AlterField(
            model_name='apitest',
            name='apitestresult',
            field=models.BooleanField(verbose_name='测试结果'),
        ),
    ]
